var questions = {
    ['HELICOPTER']: [
        {
            "questionPhoto": "justquestion.png",
            "question": 'Baggage and cargo must be properly stowed and secured, otherwise cargo shifting can cause...',
            "a": 'structural damage, angle of attack instability, speed stability.',
            "b": 'calculable instability if C.G. shifts less than 10%.',
            "c": 'uncontrollable attitudes, structural damage, risk of injury.',
            "d": 'continuous attitudes that can be corrected by pilot control inputs.',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'The power of most turbine engines is limited by...',
            "a": 'accessory gearbox and exhaust system in multi-shaft turbine engines.',
            "b": 'compressor speed, turbine exhaust temperature, and main rotor gearbox.',
            "c": 'freewheeling unit and main rotor gearbox in single-shaft turbine engines.',
            "d": 'fuel type, combustion rate, and exhaust system.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'What are the variable physical properties of the atmosphere that affect helicopter performance?',
            "a": 'Pressure, humidity, and nitrogen content',
            "b": 'Temperature, pressure, and carbon content',
            "c": 'Temperature, pressure, and humidity',
            "d": 'Pressure, humidity, and specific gravity',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'The maximum power output of helicopter piston engines is typically limited by...',
            "a": 'centrifugal clutch.',
            "b": 'gearbox of the main rotor.',
            "c": 'power turbine governor.',
            "d": 'turbine power regulator.',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'What factor has a positive effect on power required for flight?',
            "a": 'Clean rotor blades',
            "b": 'Iced helicopter airframe',
            "c": 'High-density altitude',
            "d": 'Unleaded gasoline',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'The total weight of a helicopter acts vertically through the...',
            "a": 'center of pressure.',
            "b": 'center of gravity.',
            "c": 'pivot point.',
            "d": 'neutral point.',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'What should be observed if carburetor heat is applied during a hover?',
            "a": 'Pre-ignition reduction',
            "b": 'Power loss',
            "c": 'Rotor speed increase',
            "d": 'Power gain',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'Why does Vne (never exceed speed) decrease with an increase in pressure altitude?',
            "a": 'Rotor thrust exceeds allowable structural limits',
            "b": 'True airspeed (TAS) increases',
            "c": 'Tail rotor efficiency does not ensure directional stability',
            "d": 'Ground speed (GS) decreases',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'What is the main function of the main rotor in a helicopter?',
            "a": 'Provides forward thrust',
            "b": 'Enables vertical flight',
            "c": 'Controls flight direction',
            "d": 'Maintains helicopter stability',
            "correctAnswer": 'D',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'What is rotor speed?',
            "a": 'The speed at which the rotor rotates',
            "b": 'The speed of the helicopter in level flight',
            "c": 'The speed of the wind relative to the rotor',
            "d": 'The axial speed of the rotor',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'What are the primary controls for maneuvering a helicopter in flight?',
            "a": 'Altitude and direction control',
            "b": 'Speed and tilt control',
            "c": 'Throttle and flaps control',
            "d": 'Aileron and elevator controls',
            "correctAnswer": 'D',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'What is pitch in a helicopter?',
            "a": 'Movement of the helicopter around the vertical axis',
            "b": 'Movement of the helicopter around the longitudinal axis',
            "c": 'Movement of the helicopter around the lateral axis',
            "d": 'Movement of the helicopter around the rotor axis',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'What is the primary source of propulsion in a helicopter?',
            "a": 'Aircraft engine',
            "b": 'Piston engine',
            "c": 'Electric motor',
            "d": 'Gas turbine engine',
            "correctAnswer": 'B',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": "What factors affect the lift generated by a helicopter's rotor?",
            "a": 'Flight speed and blade angle of attack',
            "b": 'Helicopter weight and rotor speed',
            "c": 'Air temperature and humidity',
            "d": 'Rotor size and blade length',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": "question_1.png",
            "question": "What does the labeled element in the helicopter cockpit photo represent?",
            "a": 'Engine controls',
            "b": 'Gearbox',
            "c": 'Lever',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": "question_2.png",
            "question": "What is this helicopter component responsible for?",
            "a": "It supplies electrical power to the helicopter's onboard systems.",
            "b": "For stabilization and control of the helicopter's flight direction.",
            "c": "It provides additional lift during takeoff and landing of the helicopter.",
            "correctAnswer": 'B',
        },
    ],
    ['PLANE']: [
        {
            "questionPhoto": "justquestion.png",
            "question": 'What is angle of attack?',
            "a": 'The angle between the chord line of an airfoil and the relative wind',
            "b": 'The angle between lift and relative wind',
            "c": 'The angle between the chord line of an airfoil and drag',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'Which aircraft has priority over the other listed aircraft?',
            "a": 'Glider',
            "b": 'Blimp',
            "c": 'Single-engine airplane',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'Topping off the tanks after the last flight of the day is a good idea because...',
            "a": 'It forces any existing water to the top of the tank away from the fuel lines to the engine',
            "b": 'It prevents fuel expansion by eliminating air space in the tanks',
            "c": 'It prevents condensation of moisture by eliminating air space in the tanks',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": "justquestion.png",
            "question": "What is V-speed?",
            "a": "Climb speed",
            "b": "Cruise speed",
            "c": "Minimum turn speed",
            "d": "Descent speed",
            "correctAnswer": "B"
        },
        {
            "questionPhoto": "justquestion.png",
            "question": "What are the three primary axes of aircraft motion?",
            "a": "Vertical axis, horizontal axis, lateral axis",
            "b": "Longitudinal axis, lateral axis, diagonal axis",
            "c": "Up-down axis, left-right axis, front-back axis",
            "d": "Long axis, short axis, medium axis",
            "correctAnswer": "A"
        },
        {
            "questionPhoto": "justquestion.png",
            "question": "What is the aircraft's shadow zone?",
            "a": "The area around the engine where aerodynamic pressure is highest",
            "b": "The area behind the wings where air resistance is lowest",
            "c": "The area behind the vertical stabilizer where the effect of aircraft yaw on controllability is minimal",
            "d": "The area just behind the wing's leading edge where the airflow is unstable",
            "correctAnswer": "D"
        },
        {
            "questionPhoto": "justquestion.png",
            "question": "What are the four primary forces acting on an aircraft in flight?",
            "a": "Lift force, gravity force, thrust force, drag force",
            "b": "Propulsion force, drag force, lateral force, centrifugal force",
            "c": "Upward force, propulsive force, centrifugal force, frictional force",
            "d": "Lift force, drag force, gravity force, lateral force",
            "correctAnswer": "A"
        },
        {
            "questionPhoto": "justquestion.png",
            "question": "What role does the elevator play in an aircraft?",
            "a": "Controls aircraft movement along the longitudinal axis (climbing and descending)",
            "b": "Controls aircraft movement along the lateral axis (banking)",
            "c": "Controls aircraft movement along the vertical axis (yawing)",
            "d": "Controls aircraft speed during landing",
            "correctAnswer": "A"
        },
        {
            "questionPhoto": "justquestion.png",
            "question": 'What are the three main components of a jet engine?',
            "a": 'Compressor, turbine, fuel tank',
            "b": 'Turbine, driveshaft, exhaust nozzle',
            "c": 'Intake valve, cylinder, piston',
            "d": 'Battery, relay, electric motor',
            "correctAnswer": 'A',
        },
        {
            "questionPhoto": 'question_1.png',
            "question": 'What does this image show?',
            "a": 'Compass',
            "b": 'Airspeed indicator',
            "c": 'Altitude indicator',
            "d": 'Altimeter',
            "correctAnswer": 'C',
        },
        {
            "questionPhoto": 'question_2.png',
            "question": 'What is the name of this cloud group?',
            "a": 'Cirrus',
            "b": 'Stratus',
            "c": 'Nimbostratus',
            "d": 'Cumulus',
            "correctAnswer": 'D',
        },
    ],
}
